### PR TITLE
TSCBasic: repair the build on Windows after #139

### PR DESCRIPTION
**Pull request by compnerd**
Import WinSDK to get access to `SwitchToThread`.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
C: @tgymnich

**Comment by neonichu** [comment]
Sorry, updating the CI had some unexpected fallout, working through it in https://github.com/apple/swift-tools-support-core/pull/148

The good news is that once that is done, we can get rid of the vendored TSC in SwiftPM.

**Review by tomerd — APPROVED** [review]
LGTM, pending CI going green

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Ah right, we still need the workspace.

**Comment by neonichu** [comment]
@swift-ci please test

**Review by neonichu — APPROVED** [review]

**Pull request merged**
