### PR TITLE
update swift-system dependency to upToNextMinor instead of upToNextMajor

### PR DESCRIPTION
**Pull request by tomerd**
motivation: align with SwiftPM and reduce risk

changes: 
* update swift-system dependency to upToNextMinor instead of upToNextMajor
* update min version of swift-system to 1.1.1

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci test

**Comment by tomerd** [comment]
@swift-ci test

**Comment by tomerd** [comment]
cc @neonichu

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/3950

@swift-ci test

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
ci failures addressed in https://github.com/apple/swift-package-manager/pull/3951

**Comment by tomerd** [comment]
apple/swift-package-manager#3950

@swift-ci test

**Pull request merged**
