### PR TITLE
Remove Gates on CMake install Targets

### PR DESCRIPTION
**Pull request by gmittert**
~SwiftPM uses USE_CMAKE_INSTALL to indicate if CMake should generate
install targets (see
https://github.com/apple/swift-package-manager/blob/main/CMakeLists.txt#L37).
This updates swift-tools-support-core to match this behaviour.~

    When bootstrapping Swift projects using CMake, we need to be able to
    install libraries to the install tree so they are available at runtime
    for installed programs to dynamically link against.

### CODE REVIEW

**Comment by gmittert** [comment]
cc @compnerd This should be nfc re windows builds.

@swift-ci please test platform

**Review by neonichu — APPROVED** [review]

**Comment by compnerd** [comment]
I think that we should be going in the opposite direction - creating the install targets unconditionally.  This will actually allow us to hollow out the bootstrap script.

**Comment by gmittert** [comment]
> I think that we should be going in the opposite direction - creating the install targets unconditionally. This will actually allow us to hollow out the bootstrap script.

That would be my preference as well. Do you know if there's any specific reason why spm defaults to not having them?

**Comment by compnerd** [comment]
I don't know why historically it did that, but, I think that we should be able to change that now given that we do want to try to simplify the bootstrap process.

**Comment by gmittert** [comment]
> I don't know why historically it did that, but, I think that we should be able to change that now given that we do want to try to simplify the bootstrap process.

Alright, I've changed this to just removing the Windows only gates.

**Review by compnerd — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please test

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
