### PR TITLE
Remove previously deprecated SQLite functionality

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Hmm, I didn't realize that this was an option.  This could allow us to rename the module in SPM as well.

**Comment by neonichu** [comment]
@swift-ci please test macOS

**Comment by neonichu** [comment]
@swift-ci please test macOS

**Pull request merged**
