### PR TITLE
update sources from SPM

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Windows CI: https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=17110&view=logs&j=b9e62f99-1a98-5ed7-01d2-f4794231ed79

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
Did a sync with  https://github.com/apple/swift-tools-support-core/pull/16

**Pull request closed without merging**
