### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by neonichu**
Remove inactive contributors and add Max Desiatov.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]
Thanks!

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by neonichu** [comment]
@swift-ci test windows

**Pull request merged**
