### PR TITLE
Adding tracing event/collection

### PR DESCRIPTION
**Pull request by virtan**
Adding structs for tracing events/collections

### CODE REVIEW

**Comment by sergiocampama** [comment]
given that this is also part of linux and windows, could you add `canImport Darwin || Glibc` checks? it seems like the pthread APIs might not be fully portable...

also, could you add some basic tests that enforce some level of the API?

**Comment by sergiocampama** [comment]
@swift-ci test

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Comment by virtan** [comment]
@swift-ci test

**Comment by sergiocampama** [comment]
@swift-ci test

**Pull request merged**
