### PR TITLE
fix flaky test

### PR DESCRIPTION
**Pull request by tomerd**
motivation: LockTests.testReadWriteFileLock can race read and write threads causing unstable results and failing tests

changes:
* write zero value to file before starting and reading or writing operations

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
@swift-ci please test

**Review by abertelrud — APPROVED** [review]

**Review by benlangmuir — APPROVED** [review]
Thanks for the quick fix, @tomerd!

**Comment by tomerd** [comment]
```
16:25:13 warning: Could not read SDKSettings.json for SDK at: /home/buildnode/jenkins/workspace/pr-swift-tools-support-core-linux/branch-main/build/buildbot_incremental/swift-linux-x86_64/stdlib/public/core
16:25:13 error: could not decode frontend target info; compiler driver and frontend executables may be incompatible
16:25:13 details: frontend: /home/buildnode/jenkins/workspace/pr-swift-tools-support-core-linux/latest_toolchain/swift-5.3-RELEASE-ubuntu16.04/usr/bin/swift
16:25:13          arguments: ["-frontend", "-print-target-info", "-target", "x86_64-unknown-linux-gnu", "-sdk", "/home/buildnode/jenkins/workspace/pr-swift-tools-support-core-linux/branch-main/build/buildbot_incremental/swift-linux-x86_64/stdlib/public/core", "-resource-dir", "/home/buildnode/jenkins/workspace/pr-swift-tools-support-core-linux/branch-main/build/buildbot_incremental/swift-linux-x86_64/lib/swift", "-runtime-compatibility-version", "none"]
16:25:13          error: key missing: CodingKeys(stringValue: "compilerVersion", intValue: nil), path: []
16:25:13 output
16:25:13 : "{
```

@shahmishal this look like some CI config issue? all PRs are failing with it

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci please test linux

**Comment by shahmishal** [comment]
@swift-ci please test linux

**Comment by tomerd** [comment]
@swift-ci please test linux

**Pull request merged**
