### PR TITLE
Clarify when we're creating a TSC Thread and not a Foundation Thread

### PR DESCRIPTION
**Pull request by DougGregor**
Fixes an ambiguity that crops up with Sendable adoption (rdar://97223378).

### CODE REVIEW

**Review by artemcm — APPROVED** [review]

**Review by phausler — APPROVED** [review]
Looks good to me!

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci test

**Comment by DougGregor** [comment]
Err...

```
[22/31][ 70%][10.290s] Linking Swift static library lib/libXcodeproj.a
Aborted by [unknown](https://ci.swift.org/user/unknown)
Sending interrupt signal to process
[23/31][ 74%][13.181s] Linking Swift
```

**Comment by DougGregor** [comment]
@swift-ci test

**Review by neonichu — APPROVED** [review]

**Pull request merged**
