### PR TITLE
WIP: Extended CI

### PR DESCRIPTION
**Pull request by neonichu**
This opts TSC in to running SwiftPM and SourceKit-LSP tests as well. Since there are some CI-specific issues to work through, we need a PR to iterate on them.

### CODE REVIEW

**Comment by neonichu** [comment]
Continuation of #148

**Comment by neonichu** [comment]
apple/swift-package-manager#2993
@swift-ci please test

**Comment by neonichu** [comment]
Linux issue is that any tests that are running an inferior `swift build` or `swift test` are not finding the PackageDescription module.

**Comment by neonichu** [comment]
The macOS job is consistenly hanging in `XcodeprojTests.XcodeProjectModelTests`

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
I wonder if the hang is related to what we were seeing in https://github.com/apple/swift-package-manager/pull/2842

**Comment by neonichu** [comment]
Going to try `bootstrap` instead of `swift-test` for the SwiftPM tests, let's see if that makes a difference.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
> Build timed out (after 83 minutes). Marking the build as failed.

**Comment by neonichu** [comment]
@swift-ci please test macOS

**Comment by neonichu** [comment]
Nice, looks like using `build-script` works fine (the Linux failure isn't related).

**Comment by neonichu** [comment]
@swift-ci please test linux

**Comment by neonichu** [comment]
@swift-ci please test linux

**Comment by neonichu** [comment]
Seems as if the Linux build is broken somehow:

> /home/buildnode/jenkins/workspace/pr-swift-tools-support-core-linux/branch-main/swift-corelibs-foundation/CoreFoundation/String.subproj/CFString.c:3552:100: error: use of undeclared identifier 'UCHAR_EMOJI_MODIFIER'

Not sure why we aren't seeing the same thing in SwiftPM's job, both should be identical now.

**Comment by MaxDesiatov** [comment]
@swift-ci please test Linux platform

**Comment by neonichu** [comment]
@swift-ci please test Linux

**Comment by neonichu** [comment]
I understand the linux issue now, the CI script was using the macOS preset also for Linux will led to system ICU being used.

**Comment by neonichu** [comment]
@swift-ci please test Linux

**Comment by neonichu** [comment]
OK, this can be closed now.

**Pull request closed without merging**
