### PR TITLE
TSCBasic: Use collection diff api for EditDistance if possible

### PR DESCRIPTION
**Pull request by PetrGuan**
Sorry this is my first PR for this. I'm not sure if I should or how to correctly commit to SPM according to the README: 

`All changes to source files in this repository need to be done in the repository of the Swift Package Manager repository ([link](https://github.com/apple/swift-package-manager)) and then copied here using the Script in Utilities/import which takes the local path to the SwiftPM directory as input (or uses ../swiftpm as default).`

### CODE REVIEW

**Comment by PetrGuan** [comment]
@swift-ci please test linux

**Comment by neonichu** [comment]
https://github.com/apple/swift-tools-support-core/pull/303 removes the outdated remark you noticed.

**Comment by tomerd** [comment]
thanks @PetrGuan can you confirm we have a test covering this functionality?

**Comment by PetrGuan** [comment]
@tomerd There's already a test in `EditDistanceTests`. But I'm not sure how to test the full code path for `if #available` and `else`, any suggestions? Or should I break it up to two functions and test each separately?

**Comment by tomerd** [comment]
right we can break into separate functions and test separately

**Comment by PetrGuan** [comment]
Thanks, just updated

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-ci test

**Comment by tomerd** [comment]
thanks @PetrGuan

**Pull request merged**
