### PR TITLE
make testSignals more robust

### PR DESCRIPTION
**Pull request by tomerd**
motivation: testSignals can hang

changes:
* do not attempt to wait on the process if it fails to start
* run each waiting operation on a seperate thread
* add timeout

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci test

**Review by abertelrud — APPROVED** [review]
Looks good to me.

**Comment by tomerd** [comment]
@swift-ci test linux

**Comment by tomerd** [comment]
@swift-ci please test linux

**Comment by tomerd** [comment]
@swift-ci please test linux

**Pull request merged**
