### PR TITLE
[Serialized diagnostics] Ignore unknown records.

### PR DESCRIPTION
**Pull request by DougGregor**
To improve forward compatibility, ignore any unknown records encountered during deserialization rather than throwing an error. libclang has behaved this way forever, and we should do the same.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please smoke test

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Review by compnerd — COMMENTED** [review]
@DougGregor where is this used?  IIRC swift-driver has a copy of the Bitcode deserialization logic.

**Comment by DougGregor** [comment]
> @DougGregor where is this used? IIRC swift-driver has a copy of the Bitcode deserialization logic.

SwiftPM has a little-used client of this (`swift package diagnose-api-breaking-changes`). swift-driver uses this version in some of its tests

**Pull request merged**
