### PR TITLE
Process: Fix stdout and stderr on Windows

### PR DESCRIPTION
**Pull request by troughton**
`stdoutData` and `stderrData` were never read. Remove them and directly update the `stdout.result` and `stderr.result` variables.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Comment by troughton** [comment]
The force-push was just changing the `var`s in the `if case let`s to `let`s to silence a warning.

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Pull request merged**
