### PR TITLE
Revert "improve process state management"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift-tools-support-core#203

This seems to have broken the Windows build:
https://compnerd.visualstudio.com/3133d6ab-80a8-4996-ac4f-03df25cd3224/_apis/build/builds/49569/logs/35

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
cc @tomerd

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by tomerd** [comment]
@compnerd i'd be okay reverting temporarily since its an improvement only, but think its something we want to bring back once we understand the windows breakage. can you tell how it broke the windows build / give guidance on how i can test it for windows via ci?

**Comment by compnerd** [comment]
@tomerd the failure is in the log above (https://compnerd.visualstudio.com/3133d6ab-80a8-4996-ac4f-03df25cd3224/_apis/build/builds/49569/logs/35); The easiest way to test on Windows is to setup a local build sadly as we do not have GHA for this.  I can kick off a one-off though if you have a PR.

**Comment by tomerd** [comment]
okay sounds good, i am ooo till monday but will look then. feel free to revert if more urgent then that

**Comment by compnerd** [comment]
I think its good to revert for the time being - we haven't had a good build of the development tools in a while now (and this would also block toolchain updates).  Can someone accept the change so that it can be merged?

**Review by neonichu — APPROVED** [review]

**Pull request merged**
