### PR TITLE
Reduce Swift Tools Version to 4.2

### PR DESCRIPTION
**Pull request by ahoppen**
Reduce the minimum required Swift tools version for TSC to 4.2.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by aciidb0mb3r** [comment]
You need to first make this PR on SwiftPM repo. See project readme.

**Pull request closed without merging**
