### PR TITLE
 [TSCUtility] Add MIPS architectures to `Triple`

### PR DESCRIPTION
**Pull request by colemancda**
Fixes https://github.com/apple/swift/issues/58204.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
Similar to the PPC case, I find the commit message misleading.  It is simply enumerating additional architectures for Triple rather than adding support for MIPS.

**Comment by colemancda** [comment]
@compnerd I can change the commit message, any suggestions?

**Comment by colemancda** [comment]
@compnerd Updated commit message

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
