### PR TITLE
Update swift-system to increase Linux compatibility

### PR DESCRIPTION
**Pull request by vlm**
* 1.2.1 contains CSystem import fixes that are required for Linux compatibility.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Review by neonichu — APPROVED** [review]

**Comment by compnerd** [comment]
Please test windows before merging this, and include SPM and LSP tests too.

**Comment by tomerd** [comment]
iirc to get this update into the toolchain, we need to update a few more spots, correct? cc @shahmishal

**Comment by compnerd** [comment]
@tomerd yes, update-checkout needs to be updated and we need to synchronise with compnerd/swift-build

**Comment by neonichu** [comment]
Looks like there's a conflict with one of the other dependencies in the toolchain:

```
+ swift test --parallel --enable-test-discovery --multiroot-data-file Utilities/ci.xcworkspace --test-product swift-tools-support-corePackageTests
warning: --multiroot-data-file is an *unsupported* option which can be removed at any time; do not rely on it
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
Fetching https://github.com/apple/swift-syntax.git
Fetched https://github.com/apple/swift-syntax.git (1.16s)
error: Dependencies could not be resolved because root depends on 'swift-system' 1.1.1..<1.2.0 and root depends on 'swift-system' 1.2.1..<1.3.0.
```

I guess because we have multiple roots, we don't get a clear error?

BTW, to test Windows and SourceKit-LSP, you can open a PR on the Swift repo and use cross repository testing with this PR.

**Comment by tomerd** [comment]
@vlm do you want to push this forward? @MaxDesiatov is updating argument parser so he can share notes on all the places that need to be changed

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65850

@swift-ci please smoke test

**Comment by yim-lee** [comment]
@swift-ci please test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65850

@swift-ci please test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65938

@swift-ci please test

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65938
https://github.com/apple/swift-package-manager/pull/6563

@swift-ci please test

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
@yim-lee i don't believe this repo supports cross repo testing, so it would need to be tested via the SwiftPM PR

**Comment by yim-lee** [comment]
https://github.com/apple/swift/pull/65938
https://github.com/apple/swift-package-manager/pull/6563

@swift-ci please test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by compnerd** [comment]
@neonichu I think that we might be able to close this after #448

**Pull request closed without merging**
