### PR TITLE
Add some noasync annotations and async overloads for improved Swift Concurrency interop

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]
Nice! 👍

**Comment by tomerd** [comment]
how safe is this given all the custom locking and dispatch usage in TSC's Process?

**Comment by tomerd** [comment]
can we also get some tests added

**Comment by jakepetroules** [comment]
> how safe is this given all the custom locking and dispatch usage in TSC's Process?

Should be fine. We're just wrapping existing completion handler APIs in continuations. The unsafe part is using the existing APIs from Swift Concurrency, because they can block the calling thread, which is really bad.

> can we also get some tests added

Done.

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please test

**Comment by jakepetroules** [comment]
@swift-ci please test

**Comment by jakepetroules** [comment]
@swift-ci please test

**Comment by jakepetroules** [comment]
@swift-ci please test

**Comment by jakepetroules** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
I always forget whether we have Windows CI set up here. If we so, looks like that job didn't run here.

**Pull request merged**
