### PR TITLE
Copy CODEOWNERS from swiftpm

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by abertelrud** [comment]
Thanks for copying this over.  Could you also update the email addresses and names in the comments section to match the listed code owners?  Thanks!

**Comment by neonichu** [comment]
Sure, but I think we should update it in SwiftPM first then.

**Comment by abertelrud** [comment]
That makes sense to me.  We can also put up a separate PR; I'll do that for both (it's not the highest priority though).

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
