### PR TITLE
Allow non-blocking file locks

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/7269
@swift-ci please test

**Comment by neonichu** [comment]
```
TSCBasicTests/FileSystemTests.swift:883: Fatal error: 'try!' expression unexpectedly raised an error: TSCBasic.FileSystemError(kind: TSCBasic.FileSystemError.Kind.unsupported, path: Optional(<AbsolutePath:"/tmp/TemporaryDirectory.bGFJkn/lockfile">))
```

Probably did something wrong in the `InMemoryFileSystem` implementation of non-blocking, this was only supposed to be thrown if we ask for a non-blocking lock which nothing should do.

**Review by MaxDesiatov — APPROVED** [review]

**Comment by neonichu** [comment]
Ah no, the issue is that I didn't fully adopt `InMemoryFileSystem` correctly.

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/7269
@swift-ci please test

**Comment by neonichu** [comment]
Changed this now such that we don't use default arguments anymore and that seems to resolve the issue.

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/7269
@swift-ci please test windows

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/7269
@swift-ci please test

**Comment by neonichu** [comment]
https://github.com/apple/swift-package-manager/pull/7269
@swift-ci please test windows

**Comment by neonichu** [comment]
```
2024-01-19 20:12:14.895.Test Suite 'FileSystemTests' started at 2024-01-19 20:12:14.895.
Test Case '-[TSCBasicTests.FileSystemTests testLocalReadWriteFile]' started./Users/ec2-user/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/Tests/TSCBasicTests/FileSystemTests.swift:334: error: -[TSCBasicTests.FileSystemTests testLocalReadWriteFile] : XCTAssertEqual failed: ("FileSystemError(kind: TSCBasic.FileSystemError.Kind.ioError(code: 17), path: Optional(<AbsolutePath:"/">))") is not equal to ("FileSystemError(kind: TSCBasic.FileSystemError.Kind.isDirectory, path: Optional(<AbsolutePath:"/">))")Test Case '-[TSCBasicTests.FileSystemTests testLocalReadWriteFile]' failed (0.375 seconds).Test Suite 'FileSystemTests' failed at 2024-01-19 20:12:15.270.
```

**Comment by neonichu** [comment]
OK, issue is present in baseline as well (https://ci.swift.org/job/pr-swift-tools-support-core-macos/359/) and I also have been seeing it locally for a while. Probably a slight behavior change between macOS versions?

**Comment by neonichu** [comment]
Fixing the test in https://github.com/apple/swift-tools-support-core/pull/460

**Comment by MaxDesiatov** [comment]
https://github.com/apple/swift-package-manager/pull/7269
@swift-ci please test

**Pull request merged**
