### PR TITLE
add AbsolutePath initializer that take RelativePath

### PR DESCRIPTION
**Pull request by tomerd**
motivation: with the deprecation of AbsolutePath::appending need a replacement API

changes:
* add AbsolutePath(:relativeTo) API vairant that takes RelativePath
* add tests

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci test

**Review by compnerd — APPROVED** [review]
I assume that this is for the case that you already have a RelativePath and want to avoid the .pathString?  Seems reasonable.  I just worry about people trying to create the relative path first (with a reference to the ancestor which would break:
~~~
AbsolutePath(RelativePath("../sibling"), relativeTo: "me")
~~~

**Comment by neonichu** [comment]
Isn't this the same as https://github.com/apple/swift-tools-support-core/blob/main/Sources/TSCBasic/Path.swift#L106?

**Comment by abertelrud** [comment]
> Isn't this the same as https://github.com/apple/swift-tools-support-core/blob/main/Sources/TSCBasic/Path.swift#L106?

That does look the same, yes.  Since it was overlooked here, maybe it is good to add the `relativeTo:` label (and deprecate the old one?) so it's more clear that it exists?

**Comment by tomerd** [comment]
@abertelrud @neonichu they have similar signature but the new one goes through the "Windows fix" while the old one does not. Maybe the right thing is to make the old one private? this way we can preserve the integrity of the API?

**Comment by abertelrud** [comment]
> @abertelrud @neonichu they have similar signature but the new one goes through the "Windows fix" while the old one does not. Maybe the right thing is to make the old one private? this way we can preserve the integrity of the API?

That's a good point — yes, having them go through the path normalization after appending the relative path is the right thing to do.  So that sounds like a good plan.

**Pull request closed without merging**
