### PR TITLE
build: auto-vendor SwiftSystem when not provided

### PR DESCRIPTION
**Pull request by compnerd**
When SwiftSystem is not provided to be built against explicitly (i.e.
`-D SwiftSystem_DIR=...`), vendor a copy of SwiftSystem to allow the
library to be built by including and building its dependencies.  This
behaviour is similar to how SPM based builds function.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@tomerd can we just cut the swift-system dependency actually? IIRC, it was eagerly added in anticipation of using its path type but we have no plans to actually use that anymore.

**Comment by compnerd** [comment]
@neonichu hmm, we can for the vendoring path, but the non-vendored path needs it as imports are public still, and TSC has a dependency on System.

**Comment by neonichu** [comment]
Right, what I mean is that the dependency doesn't actually have any purpose. I opened a PR to remove it: https://github.com/apple/swift-tools-support-core/pull/448

**Pull request closed without merging**
