### PR TITLE
[TSCUtility] Add PowerPC 32-bit architecture to `Triple`

### PR DESCRIPTION
**Pull request by colemancda**
Fixes https://github.com/apple/swift/issues/58206

### CODE REVIEW

**Comment by colemancda** [comment]
@MaxDesiatov Could you review please?

**Comment by MaxDesiatov** [comment]
I'll kick off CI, but I think someone else would have to review before the PR is merged.

**Review by neonichu — APPROVED** [review]

**Review by compnerd — COMMENTED** [review]
While the change itself is fine, I find the commit message to be pretty misleading.  It is extending the enumerated architecture list in Triple, but doesn't explicitly do anything to add support for PPC.

**Review by compnerd — APPROVED** [review]

**Comment by colemancda** [comment]
@compnerd Updated commit message

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
