### PR TITLE
add isReadable and isWritable APIs to FileSystem

### PR DESCRIPTION
**Pull request by tomerd**
motivation: users often need to check if a path is readable and / or writable

changes:
* add isReadable and isWritable APIs to FileSystem
* implement in relevant FileSystem implementations
* add tests

### CODE REVIEW

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/4077

@swift-ci test

**Comment by tomerd** [comment]
apple/swift-package-manager#4077

@swift-ci test

**Review by abertelrud — APPROVED** [review]

**Review by yim-lee — APPROVED** [review]

**Comment by weissi** [comment]
@tomerd / @jakepetroules this broke the API and thus should've been tagged as 0.3.0 not 0.2.5

**Comment by tomerd** [comment]
@weissi @jakepetroules was not aware there is any semantic versioning done on this library! SwiftPM, Driver and LSP which are the main consumers both depend on it in a branch-revision-locked way (🙄 I know) so there isn't much effort put into evolving APIs in a clean semantic way. fwiw my goal is to deprecate this library all together and not continue to invest in it

@jakepetroules you seem to have been the one tagging this library? would be good to better understand to what end its being tagged, and how to better coordinate if such tagging is in fact needed and the implications on versioning and Api evolution

**Comment by weissi** [comment]
> @weissi @jakepetroules was not aware there is any semantic versioning done on this library! 

Well, it's 0.x so SemVer says "yolo", ie. you can say it's okay to break the API between 0.2.4 and 0.2.5. However, usually if you do do a breaking change, you'd increment the minor (ie. 0.2.4  -> 0.3).

> SwiftPM, Driver and LSP which are the main consumers both depend on it in a branch-revision-locked way (🙄 I know) so there isn't much effort put into evolving APIs in a clean semantic way. fwiw my goal is to deprecate this library all together and not continue to invest in it

Totally cool, I'm not arguing for us trying to not break the API, I'm arguing for using a new minor version for breaking changes (and not just a patch bump).


> @jakepetroules you seem to have been the one tagging this library? would be good to better understand to what end its being tagged, and how to better coordinate if such tagging is in fact needed and the implications on versioning and Api evolution

IMHO we should try to bump the minor for breaking changes but I don't think we need to have strict rules for API evolution. Breaking is fine by me but we should make that fact visible through version numbers.

**Comment by tomerd** [comment]
this sounds fine, but I was not even aware its being tagged, so we need better coordination here

**Pull request merged**
