### PR TITLE
build: simplify the build rules with newer CMake (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
Swift now requires CMake 3.19.6 as a minimum version.  Assume that we can use CMake newer than 3.16 and simplify the build rules.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Review by MaxDesiatov — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Pull request merged**
