### PR TITLE
Add an overload of `exec(path:args:)` which returns Never

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Review by BenchR267 — APPROVED** [review]

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
The Linux failure is known but we don't know yet why it is happening and how to fix it.

**Review by neonichu — APPROVED** [review]

**Comment by tomerd** [comment]
> The Linux failure is known but we don't know yet why it is happening and how to fix it.

@neonichu @abertelrud is one of you looking into it? is it a test issue or a code issue?

**Comment by neonichu** [comment]
> @neonichu @abertelrud is one of you looking into it? is it a test issue or a code issue?

I was looking into this quite a bit and haven't been able to reproduce it myself (using a prebuilt 5.5 toolchain instead of building one myself). I'm pretty sure it is just a test issue since the underlying feature seems to work fine in that same configuration for me (5.5 on Ubuntu 16).

**Pull request merged**
