### PR TITLE
CODE_OF_CONDUCT

### PR DESCRIPTION
**Pull request by gaushikmr**

### CODE REVIEW

**Comment by neonichu** [comment]
Adding the code of conduct to the repo sounds like a good idea, but we should use the same as https://github.com/apple/swift/blob/master/CODE_OF_CONDUCT.md

**Comment by gaushikmr** [comment]
@neonichu ok

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Pull request merged**
