### PR TITLE
mark argument parser as deprecated

### PR DESCRIPTION
**Pull request by tomerd**
motivation: swift-argument-parser replaces this custom functionality, and SWiftPM has long migrated over

changes:
* mark all argument parsing APIs as deprecated
* remove the "TSCTestSupportExecutable" which is not used and uses the custom argument parser

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
> 12:35:14 Fatal error: 'try!' expression unexpectedly raised an error: could not find executable for '/Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/TSCTestSupportExecutable': file TSCBasicTests/LockTests.swift, line 41

Looks like it is used by some test :)

**Comment by tomerd** [comment]
interesting, I guess those dont run locally!

**Comment by tomerd** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
> Ha! they passed locally since there was a cached executable :D

That seems like a bug in itself. At least in Xcode, stale file removal should kick in and remove the executable. In `swift build`, we haven't implemented stale file removal, so there it would be expected.

**Comment by tomerd** [comment]
makes sense -- I was testing in Xcode

**Review by neonichu — APPROVED** [review]

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
