### PR TITLE
TSCBasic: repair build after #125

### PR DESCRIPTION
**Pull request by compnerd**
The file was misnamed but was not caught during review.  This fixes the
file name to repair the build.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @sergiocampama

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
This is going to repair the build and has NFC, Im going to merge it, and can address comments post-commit.

**Comment by sergiocampama** [comment]
yeah, sorry about that, caught it on my next PR, and was surprised that CI didn't catch it

**Comment by neonichu** [comment]
CI of TSC is a bit basic right now, it only does `swift build`. I'm planning to enhance this and also test the CMake build as well as downstream projects like SwiftPM and SourceKit-LSP as part of removing the vendored copy from SwiftPM.

**Pull request merged**
