### PR TITLE
Add base64url helper methods for Array/ArraySlice of [UInt8]

### PR DESCRIPTION
**Pull request by dmbryson**

### CODE REVIEW

**Comment by dmbryson** [comment]
Moving from llbuild2, as requested.

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
🤔 is swift-ci still down?

**Comment by aciidb0mb3r** [comment]
@swift-ci test

**Comment by aciidb0mb3r** [comment]
This repo just has regular tests (no “smoke” tests)

**Comment by dmbryson** [comment]
> @swift-ci please 🔥test

**Pull request merged**
