### PR TITLE
[5.6] store lock files in temporary directory (#273)

### PR DESCRIPTION
**Pull request by tomerd**
5.6 cherry pick of #273

### CODE REVIEW

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/3965

@swift-ci please test

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/3965

@swift-ci please test

**Comment by tomerd** [comment]
CI failures seem to be due to network issues on CI nodes

**Comment by tomerd** [comment]
apple/swift-package-manager#3965

@swift-ci please test

**Comment by tomerd** [comment]
cc @abertelrud for 5.6 review

**Review by abertelrud — APPROVED** [review]

**Pull request merged**
